export const CHANGE_THEME = "CHANGE_THEME";
export const THEME_DARK = "dark";
export const THEME_LIGHT = "light";

export const ADD_WAREHOUSE = "ADD_WAREHOUSE";
export const REMOVE_WAREHOUSE = "EMOVE_WAREHOUSE";

export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const REMOVE_PRODUCTS = "EMOVE_PRODUCTS";
export const CHANGE_PRODUCTS_INFO = 'CHANGE_PRODUCTS_INFO';

export const ADD_PRODUCTS_TO_WAREHOUSE = 'ADD_PRODUCTS_TO_WAREHOUSE';
export const REMOVE_PRODUCTS_FROM_WAREHOUSE = 'REMOVE_PRODUCTS_FROM_WAREHOUSE';

export const CHANGE_WAREHOUSE_INFO = 'CHANGE_WAREHOUSE_INFO';


